matrix:
  fast_finish: true
  include:
    - os: osx
      compiler: clang
    - os: linux
      compiler: gcc-8
      env:
        - LDFLAGS="-Wl,-z,relro"
        - CFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security"
        - CPPFLAGS="-Wdate-time -D_FORTIFY_SOURCE=2"
    - os: linux
      compiler: gcc
      env:
        - LDFLAGS=
        - TEST_INDENT=yes
    - os: linux
      compiler: gcc
      env:
        - LDFLAGS=-static
    - os: linux
      compiler: clang
      env:
        - LDFLAGS=
    - os: linux
      compiler: clang
      env:
        - LDFLAGS=-static
    - os: linux
      compiler: musl-gcc
      env:
        - LDFLAGS=
    - os: linux
      compiler: musl-gcc
      env:
        - LDFLAGS=-static
# Adding ppc64le jobs
    - os: linux
      arch: ppc64le
      dist: bionic
      compiler: gcc-8
      env:
        - LDFLAGS="-Wl,-z,relro"
        - CFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security"
        - CPPFLAGS="-Wdate-time -D_FORTIFY_SOURCE=2"
    - os: linux
      arch: ppc64le
      dist: bionic
      compiler: gcc
      env:
        - LDFLAGS=
    - os: linux
      arch: ppc64le
      dist: bionic
      compiler: gcc
      env:
        - LDFLAGS=-static
    - os: linux
      arch: ppc64le
      dist: bionic
      compiler: clang
      env:
        - LDFLAGS=
    - os: linux
      arch: ppc64le
      dist: bionic
      compiler: clang
      env:
        - LDFLAGS=-static
    - os: linux
      arch: ppc64le
      dist: bionic
      compiler: musl-gcc
      env:
        - LDFLAGS=
    - os: linux
      arch: ppc64le
      dist: bionic
      compiler: musl-gcc
      env:
        - LDFLAGS=-static

language: c

# Use a container Travis
sudo: false

before_install:
  - if [[ "$TEST_INDENT" = "yes" ]]; then indent -kr -i8 src/node/*.c ; fi
  - if [[ "$TEST_INDENT" = "yes" ]]; then indent -kr -i8 src/plugins/*.c ; fi
  - git diff
  - git diff --quiet
install:
  - ./getversion
  - autoreconf -i -I m4

script: ./configure && make -j2

notifications:
  irc: "irc.oftc.net#munin"

# Travis -> Coverity
env:
  global:
    - secure: "CNXrpwGgWHhD9894gMeKqlt/5eeKJ+J764jRV685JWV/5OrHeWqEfAp+onX/B+RUCl5DrFpblyQl2K6IDTABolkY4Vy/kvZHB5Y2XhyXu3U6RzQwdH3xo9olJQ+UcGzNOc1YOqSWzkDG2JbR9HthgyWgMjbvePXn5AKRGUTAasI="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - musl-tools
      - indent
      - gcc-8
  homebrew:
    packages:
      - gnu-indent

  coverity_scan:
    project:
      name: munin-monitoring/munin-c
      version: 0.0.9
      description: Munin node

    notification_email: steve.schnepp@gmail.com
    build_command_prepend: ./configure
    build_command: make -j2
    branch_pattern: coverity_scan
