language: c
compiler:
  - gcc
  - clang
  - musl-gcc

# Use a container Travis
sudo: false

install:
  - ./getversion
  - autoreconf -i -I m4

script: ./configure && make -j2

notifications:
  irc: "irc.oftc.net#munin"

# Travis -> Coverity
env:
  global:
    - secure: "CNXrpwGgWHhD9894gMeKqlt/5eeKJ+J764jRV685JWV/5OrHeWqEfAp+onX/B+RUCl5DrFpblyQl2K6IDTABolkY4Vy/kvZHB5Y2XhyXu3U6RzQwdH3xo9olJQ+UcGzNOc1YOqSWzkDG2JbR9HthgyWgMjbvePXn5AKRGUTAasI="

addons:
  apt:
    packages:
      - musl-tools

  coverity_scan:
    project:
      name: munin-monitoring/munin-c
      version: 0.0.9
      description: Munin node

    notification_email: steve.schnepp@gmail.com
    build_command_prepend: ./configure
    build_command: make -j2
    branch_pattern: coverity_scan
